### PR TITLE
fix: allow configuration of logging paths and defaults to stdout

### LINKED ISSUE #1801: OpenFGA is logging to `stderr`
### Checklist

- [X] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [X] I have searched the [OpenFGA Community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

This was originally reported in Slack: https://cloud-native.slack.com/archives/C06G1NNH47N/p1721883467423289

```go
[29/07/24 10:49:29] ~/GitHub/openfga (main) $ make dev-run
 🚀  Installing the OpenFGA binary within /Users/maria.inesparnisari/go/bin  
 🚀  Starting OpenFGA server                                                 
==> Running OpenFGA with In-Memory data storage
2024/07/29 10:49:34 Running build command!
2024/07/29 10:49:35 Build ok.
2024/07/29 10:49:35 Restarting the given command.
2024/07/29 10:49:35 stderr: 2024-07-29T10:49:35.852-0700        INFO    using 'memory' storage engine
2024/07/29 10:49:35 stderr: 2024-07-29T10:49:35.852-0700        INFO    using 'preshared' authentication
2024/07/29 10:49:35 stderr: 2024-07-29T10:49:35.852-0700        WARN    gRPC TLS is disabled, serving connections using insecure plaintext
2024/07/29 10:49:35 stderr: 2024-07-29T10:49:35.852-0700        INFO    📈 starting prometheus metrics server on '0.0.0.0:2112'
2024/07/29 10:49:35 stderr: 2024-07-29T10:49:35.852-0700        INFO    starting openfga service...    {"version": "dev", "date": "unknown", "commit": "none", "go-version": "go1.22.5", "config": {"ListObjectsDeadline":3000000000,"ListObjectsMaxResults":1000,"ListUsersDeadline":3000000000,"ListUsersMaxResults":1000,"MaxTuplesPerWrite":100,"MaxTypesPerAuthorizationModel":100,"MaxAuthorizationModelSizeInBytes":262144,"MaxConcurrentReadsForListObjects":4294967295,"MaxConcurrentReadsForCheck":4294967295,"MaxConcurrentReadsForListUsers":4294967295,"MaxConditionEvaluationCost":100,"ChangelogHorizonOffset":0,"Experimentals":[],"ResolveNodeLimit":25,"ResolveNodeBreadthLimit":100,"RequestTimeout":3000000000,"Datastore":{"Engine":"memory","Username":"","MaxCacheSize":100000,"MaxOpenConns":30,"MaxIdleConns":10,"ConnMaxIdleTime":0,"ConnMaxLifetime":0,"Metrics":{"Enabled":false}},"GRPC":{"Addr":"0.0.0.0:8081","TLS":{"Enabled":false,"CertPath":"","KeyPath":""}},"HTTP":{"Enabled":true,"Addr":"0.0.0.0:8080","TLS":{"Enabled":false,"CertPath":"","KeyPath":""},"UpstreamTimeout":5000000000,"CORSAllowedOrigins":["*"],"CORSAllowedHeaders":["*"]},"Authn":{"Method":"preshared","Issuer":"","IssuerAliases":[],"Audience":""},"Log":{"Format":"text","Level":"info","TimestampFormat":"Unix"},"Trace":{"Enabled":false,"OTLP":{"Endpoint":"0.0.0.0:4317","TLS":{"Enabled":false}},"SampleRatio":0.2,"ServiceName":"openfga"},"Playground":{"Enabled":true,"Port":3000},"Profiler":{"Enabled":false,"Addr":":3001"},"Metrics":{"Enabled":true,"Addr":"0.0.0.0:2112","EnableRPCHistograms":false},"CheckQueryCache":{"Enabled":false,"Limit":10000,"TTL":10000000000},"DispatchThrottling":{"Enabled":false,"Frequency":10000,"Threshold":100,"MaxThreshold":0},"CheckDispatchThrottling":{"Enabled":false,"Frequency":10000,"Threshold":100,"MaxThreshold":0},"ListObjectsDispatchThrottling":{"Enabled":false,"Frequency":10000,"Threshold":100,"MaxThreshold":0},"RequestDurationDatastoreQueryCountBuckets":["50","200"],"RequestDurationDispatchCountBuckets":["50","200"],"CheckTrackerEnabled":false}}
2024/07/29 10:49:35 stderr: 2024-07-29T10:49:35.852-0700        INFO    🚀 starting gRPC server on '0.0.0.0:8081'...
2024/07/29 10:49:35 stderr: 2024-07-29T10:49:35.853-0700        INFO    🛝 starting openfga playground on http://localhost:3000/playground
2024/07/29 10:49:35 stderr: 2024-07-29T10:49:35.853-0700        INFO    🚀 starting HTTP server on '0.0.0.0:8080'...
2024/07/29 10:49:35 stderr: 2024-07-29T10:49:35.853-0700        WARN    HTTP TLS is disabled, serving connections using insecure plaintext

```

### Expectation

Logs to stdout

### Reproduction

```make dev-run```

### Store data

_No response_

### OpenFGA version

1.5.7

### How are you running OpenFGA?

As a binary

### What datastore are you using?

In-Memory

### OpenFGA Flags

no

### Logs

_No response_

### PR DESCRIPTION
**Pull request by senojj**
Adds a logging option function for configuring logging paths.

## Description
defaults to stdout

## References

fixes #1801 

## Review Checklist
- [ ] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Comment by adriantam** [comment]
Is there any case we want to write to stderr even when system is configured for writing to stdout?

**Review by miparnisari — APPROVED** [review]

**Comment by senojj** [comment]
> Is there any case we want to write to stderr even when system is configured for writing to stdout?

You have a couple of options:
1. add both "stderr" and "stdout" as values for the option (it will log to both)
2. redirect the process stdout to stderr.

In order to conditionally log to different outputs, you would need to configure separate logging cores and pass them to a tee logging core.

File: pkg/logger/logger.go [hunk 1]
```diff
@@ -100,6 +100,7 @@ type OptionsLogger struct {
 	format          string
 	level           string
 	timestampFormat string
+	outputPaths     []string
```
Comment (miparnisari) [inline pkg/logger/logger.go:103]: @senojj if we want to expose this to end users we have to introduce a new server flag
