### PR TITLE
fix: the misconception between 'migration timeout' and 'database connection timeout'

### LINKED ISSUE #774: Fix docs for `./openfga migrate --timeout`
Right now:

```shell
[24/05/23 5:04:06] ~/GitHub/openfga-main (main) $ ./openfga migrate --help
The migrate command is used to migrate the database schema needed for OpenFGA.

Usage:
  openfga migrate [flags]

Flags:
...
      --timeout duration          a timeout after which the migration process will terminate (default 1m0s)
...
```

But in the code:

https://github.com/openfga/openfga/blob/11797960cc3e3040785d5f19f02c1d786d9a3f97/cmd/migrate.go#L99-L111

This is only putting a cap on the time spent contacting the database. So we should either fix the documentation to say `a timeout for the time migrate takes to connect to the DB` or fix the code so that the whole migration is allowed to take 1 minute and no more 🤔

### PR DESCRIPTION
**Pull request by gabrielbussolo**
## Description
simply fix #774 adding a more coherent description for the timeout flag.

Was suggested by @jon-whit the separation between db timeout and migration timeout on https://github.com/openfga/openfga/issues/774#issuecomment-1563085833 but as noticed in https://github.com/pressly/goose/issues/576 goose does not provide a timeout mechanism neither accepts a context as parameter (which could be potentially a `context.WithTimeout`).

So to avoid a kludge solution and address the main issue, I just adjusted the flag description.

## Review Checklist
- [ ] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [ ] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

File: cmd/migrate/migrate.go [hunk 1]
```diff
@@ -39,7 +39,7 @@ func NewMigrateCommand() *cobra.Command {
 	flags.String(datastoreEngineFlag, "", "(required) the datastore engine that will be used for persistence")
 	flags.String(datastoreURIFlag, "", "(required) the connection uri of the database to run the migrations against (e.g. 'postgres://postgres:password@localhost:5432/postgres')")
 	flags.Uint(versionFlag, 0, "the version to migrate to (if omitted the latest schema will be used)")
-	flags.Duration(timeoutFlag, 1*time.Minute, "a timeout after which the migration process will terminate")
+	flags.Duration(timeoutFlag, 1*time.Minute, "a timeout for the time it takes the migrate process to connect to the DB")
```
Comment (jon-whit) [inline cmd/migrate/migrate.go:42]: Please avoid the acronym here and just say "database"

**Review by jon-whit — APPROVED** [review]

File: cmd/migrate/migrate.go (hunk 1 above)
Comment (gabrielbussolo) [reply cmd/migrate/migrate.go]: @jon-whit sure thing, updated, and also rebased the branch
