### PR TITLE
fix: reverse expansion with indirect computed userset relationship

### LINKED ISSUE #602: Bug: Computed userset not evaluated properly for listobject
For the following model
```
model
  schema 1.1
type folder
  relations
    define can_view: viewer
    define parent: [folder]
    define viewer: [user] or viewer from parent
type user
```

With the following tuples
```
folder:a#viewer@user:anne
folder:b#parent@folder:a
```

The call `ListObjects( type: folder, relation: can_view, user: user:anne )` returns only `[folder:a]`

We expect `[folder:a,folder:b]`

Note that this is isolated to be in the reverseExpand implementation as 
```
model
  schema 1.1
type folder
  relations
    define banned: [user]
    define can_view: viewer but not banned
    define parent: [folder]
    define viewer: [user] or viewer from parent
type user
``` 
produces the correct result.

Note that the the call `ListObjects( type: folder, relation: viewer, user: user:anne )` returns `[folder:a, folder:b]` as expected

### PR DESCRIPTION
**Pull request by jon-whit**
## Description
Fixes the `RelationshipIngresses` computation of indirectly related relationships through computed usersets. This fixes a known bug with ListObjects that uses reverse expansion.

## References
Fixes #602 

## Review Checklist
- [ ] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [ ] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

File: internal/graph/graph.go [hunk 1]
```diff
@@ -167,21 +167,31 @@ func (g *ConnectedObjectGraph) findIngressesWithRewrite(
 
 		return res, nil
 	case *openfgapb.Userset_ComputedUserset: // e.g. target = define viewer as writer
+
+		var ingresses []*RelationshipIngress
+
 		// if source=document#writer
 		if target.GetType() == source.GetType() && t.ComputedUserset.GetRelation() == source.GetRelation() {
```
Comment (miparnisari) [inline internal/graph/graph.go:174]: this line and line 214 are very similar, any chance of extracting it into a function that has a meaningful name?

**Review by adriantam — APPROVED** [review]

**Comment by adriantam** [comment]
Can you take a look at https://github.com/openfga/openfga/actions/runs/4358230410/jobs/7618535157#step:5:43?

File: internal/graph/graph.go (hunk 1 above)
Comment (jon-whit) [reply internal/graph/graph.go]: Renamed the variables to `sourceRelMatchesRewritten` because this condition indicates that the source relationships matches the rewritten relationship (on the computed_userset).

**Review by miparnisari — APPROVED** [review]
