### PR TITLE
fix: support URI schemes in OTLP endpoint configuration

### LINKED ISSUE #2970: Support URIs in OTEL_EXPORTER_OTLP_ENDPOINT
### Checklist

- [x] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [x] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [x] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [x] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [x] I have searched the [OpenFGA Community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [x] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

Hi!

We are using OpenFGA in Azure Container Apps. We have been hard coding the flag `--trace-otlp-endpoint=k8se-otel.k8se-apps.svc.cluster.local:4317` but since OpenFGA `v1.11.3` the `OTEL_EXPORTER_OTLP_ENDPOINT` is now supported. We just upgraded to `v1.11.6` and tried it out, got the following error:
> traces export: exporter export timeout: rpc error: code = Unavailable desc = invalid target address http://k8se-otel.k8se-apps.svc.cluster.local:4317, error info: address http://k8se-otel.k8se-apps.svc.cluster.local:4317:443: too many colons in address

The environment variable in Azure Container Apps is set to `http://k8se-otel.k8se-apps.svc.cluster.local:4317` and I guess it's not supported to have the `http://` with how OpenFGA parses it.

The workaround for us is just to go back to using the hard coded flag.

### OpenFGA version

v1.11.6

### How are you running OpenFGA?

In Kubernetes

### What datastore are you using?

Postgres

### OpenFGA Flags

--playground-enabled=false --authn-method=oidc --authn-oidc-issuer=zeissuer --authn-oidc-audience=zeaudience --datastore-engine=postgres --datastore-uri=postgresql://zefqdn:5432/$zedb?sslmode=require --datastore-username=zeuser --log-format=json --log-level=info --trace-enabled=true --trace-otlp-endpoint=k8se-otel.k8se-apps.svc.cluster.local:4317 --trace-sample-ratio=1 --trace-service-name=zeservice

### Logs

traces export: exporter export timeout: rpc error: code = Unavailable desc = invalid target address http://k8se-otel.k8se-apps.svc.cluster.local:4317, error info: address http://k8se-otel.k8se-apps.svc.cluster.local:4317:443: too many colons in address

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
## Description

`OTEL_EXPORTER_OTLP_ENDPOINT` uses full URIs (e.g. `http://host:4317`) per the OpenTelemetry spec, but `otlptracegrpc.WithEndpoint()` expects a bare `host:port`. This caused:

```
too many colons in address http://host:4317:443
```

### What changed

- **`ParseOTLPEndpoint()`** — strips `http://` or `https://` from the endpoint, returning the bare authority and whether the scheme indicates TLS (`true` for `https://`).
- **`ResolveOTLPSecurity()`** — `return configSecure || schemeSecure`. TLS is used if either the config flag or `https://` scheme says so.
- Startup log now shows the resolved endpoint and effective TLS state.

### Backward compatibility

No breaking changes. Bare `host:port` values behave identically — `schemeSecure` is `false`, so the existing `--trace-otlp-tls-enabled` flag controls TLS as before.

| Endpoint | `--trace-otlp-tls-enabled` | Effective TLS |
|---|---|---|
| `collector:4317` | `false` | `false` |
| `collector:4317` | `true` | `true` |
| `http://collector:4317` | `false` | `false` |
| `https://collector:4317` | `false` | `true` |

## Related Issue(s)

Fixes #2970

## How to test

```bash
go test ./internal/telemetry/ -v
```

For manual validation: set `OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317` with `--trace-enabled=true` and verify traces export without the `"too many colons"` error.

<details><summary>Documentation follow-up (openfga.dev)</summary>

The [Tracing section](https://openfga.dev/docs/getting-started/setup-openfga/configure-openfga#tracing) should note that `OTEL_EXPORTER_OTLP_ENDPOINT` / `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` accept full URIs, and that an `https://` scheme enables TLS regardless of `--trace-otlp-tls-enabled`.

</details>

### CODE REVIEW

**Comment by senojj** [comment]
Thanks for taking the time to put together a pull request!

I see that the `ResolveOTLPInsecure` code prioritizes the absence of TLS in the URL's scheme over the presence of TLS enablement in the configuration.Ideally, the code should prioritize the most restrictive of the options (the most secure).

For example, if the scheme is "http", and TLS is enabled in the configuration, then the TCP connection should use TLS. If the scheme is "https" and TLS is not enabled in the configuration, then the TCP connection should use TLS.

File: internal/telemetry/tracing.go [hunk 1]
```diff
@@ -52,6 +53,52 @@ type customTracer struct {
...
+// is returned unchanged.
+//
+// The second return value conveys the security mode implied by the URI scheme:
+//   - *true  — http:// scheme, insecure connection
+//   - *false — https:// scheme, secure (TLS) connection
+//   - nil    — no recognized scheme, fall back to explicit TLS configuration
+//
+// When non-nil, the scheme takes precedence over any explicit TLS flag.
+// See [ResolveOTLPInsecure] for the full precedence logic.
+func ParseOTLPEndpoint(endpoint string) (string, *bool) {
```
Comment (senojj) [inline internal/telemetry/tracing.go]: The zero value for the returned `bool` is useful here; either the scheme specified transport layer security (`true`), or it did not (`false`). There is no need to make it a pointer in order to represent a third state.

File: internal/telemetry/tracing.go [hunk 2]
```diff
@@ -52,6 +53,52 @@ type customTracer struct {
...
+// ResolveOTLPInsecure determines whether the OTLP connection should be
+// insecure. When schemeInsecure is non-nil (from [ParseOTLPEndpoint]), the URI
+// scheme takes precedence over the configured flag.
+func ResolveOTLPInsecure(configInsecure bool, schemeInsecure *bool) bool {
+	if schemeInsecure != nil {
+		return *schemeInsecure
+	}
+	return configInsecure
+}
+
```
Comment (senojj) [inline internal/telemetry/tracing.go]: The logic can be inverted for the input parameters, making this simple call:
```go
func ResolveOTLPSecurity(configSecure, schemeSecure bool) bool {
    return configSecure || schemeSecure
}
```

**Comment by Siddhant-K-code** [comment]
Thanks @senojj for suggestions. I’ve addressed your suggestions in 3d9a92a

**Comment by Siddhant-K-code** [comment]
The `go-bench` failure is unrelated to this PR - we don't touch any benchmarked code, and the same job is flaky on main as well. Re-running should clear it.

**For Codecov:** patch coverage is 90%. The 2 uncovered lines are inside `MustNewTracerProvider`, which uses `grpc.WithBlock()` and panics on connection failure — it requires a live OTLP collector to exercise. All testable logic (`ParseOTLPEndpoint` and `ResolveOTLPSecurity`) has full coverage with 17 test cases.
