### PR TITLE
fix: `cache_item_count` metric overcounting

### LINKED ISSUE #2944: possible double-increment in cache item count metric
### Checklist

- [x] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [x] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [x] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [x] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [x] I have searched the [OpenFGA Community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [x] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

Currently, the `InMemoryLRUCache` implementation blindly increments the cache item count on any call to `(InMemoryLRUCache).Set`. However, the Theine library used internally will always update any existing key's value in place, extending its TTL. In this scenario, the blind increment of cache item count creates an invalid count, reporting more items than actually exist within the cache.

Credit for the find of this bug goes to: @evanmay

### OpenFGA version

1.11.6

### How are you running OpenFGA?

As a binary

### What datastore are you using?

In-Memory

### OpenFGA Flags

no

### Logs

_No response_

### PR DESCRIPTION
**Pull request by justincoh**
#### What problem is being solved?
Our cache code was improperly incrementing the `cache_item_count` metric by blindly incrementing on any `cache.Set` call, even if it was for an overwrite. This caused the metric to steadily increase over time like so:

image

Example: Calling `cache.Set("key", {random_ulid})` 1000 times would make it seem like there were 1000 items in the cache, even though there is actually only one.

#### What changes are made to solve it?
Rather than track cache_item_count ourselves via `.Inc()` and `.Dec()` calls, use the cache client's built in `.EstimatedSize()` method.

## References

Fixes #2944 

## Review Checklist
- [ ] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [ ] The correct base branch is being used, if not `main`
- [x] I have added tests to validate that the change in functionality is working as expected

## Bug Fixes
- Fixed a metrics accuracy issue where cache item count was incorrectly incrementing when overwriting existing entries, which was causing the counter to drift upwards over time.

### CODE REVIEW

File: pkg/storage/cache.go [hunk 1]
```diff
@@ -163,8 +163,17 @@ func (i InMemoryLRUCache[T]) Set(key string, value T, ttl time.Duration) {
...
+
+	// If we're overwriting a key, we don't want to increment metrics later
+	_, isOverwrite := i.client.Get(key)
+
+	// Ignore the boolean return here as we always pass cost=1 and items are always admitted
 	i.client.SetWithTTL(key, value, 1, ttl)
 
+	if isOverwrite {
+		return
+	}
```
[the remark this answers is not in the document]
Comment (justincoh) [reply pkg/storage/cache.go]: This is a valid point, but I'm not sure I want to add a lock into a path this hot just for the sake of 100% metric accuracy; I think this risk is acceptable for the sake of performance.

**Review by adriantam — COMMENTED** [review]
As discussed offline, we should consider using EstimatedSize() instead of tracking it ourselves.  The trade off is that we will lose entity type visibility.

File: pkg/storage/cache.go [hunk 2]
```diff
@@ -133,7 +133,6 @@ func NewInMemoryLRUCache[T any](opts ...InMemoryLRUCacheOpt[T]) (*InMemoryLRUCac
 			entityLabel = unspecifiedLabel
 		}
 
-		cacheItemCount.WithLabelValues(entityLabel).Dec()
```
Comment (adriantam) [inline pkg/storage/cache.go:136]: Do we want to update with the estimated size?

Comment (justincoh) [reply pkg/storage/cache.go:136]: We don't need to, and we actually couldn't do it in here. 

This RemovalListener is passed to the cache builder before the cache client is constructed, so at this point there is no cache `client` instance with which to call `client.EstimatedSize()`.

Even without a metric call here though, the new configuration calling `cacheItemCount.Set()` is a suitable replacement for both `Inc()` and `Dec()`, since it can both increase and decrease the metric. Having `cacheItemCount.Set` called inside our `cache.Set` method should keep this metric very close to real-time since cache.Set is a very hot path, and it's called far more often than the removalListener (which only hits on eviction, expiration or removal).

**Review by adriantam — DISMISSED** [review]
