### PR TITLE
fix: handle converting NULL to string condition name

### LINKED ISSUE #1211: Upgrading to 1.3.8 caused: sql: Scan error on column index 5, name "condition_name": converting NULL to string is unsupported
**Summary**

Immediately after upgrading to 1.3.8 from 1.3.7 we started getting internal server errors. Rolling back to 1.3.7 resolved the issue. In the logs we found the error shown below.

**OpenFGA version or commit**

Immediately after upgrading to 1.3.8

**Store data**
-

**Other data**

- docker on AWS ECS
- Postgres
- Are you running OpenFGA with any configuration overrides or with any of the flags mentioned in `./openfga run --help`?
- Logs:

Example check request:
```
2023-12-05T01:11:41.242Z	ERRORrpc error: code = Code(4000) desc = Internal Server Error
{"grpc_service": "openfga.v1.OpenFGAService", "grpc_method": "Check", "grpc_type": "unary", "request_id": "e27dc9cb-d13a-4537-b375-b14fca90fb9a", "user_agent": "openfga-sdk js/0.2.10", "raw_request": {"store_id":"01H92CEC8HDM58GWGEBRWPQHSS","tuple_key":{"user":"user:7fd5822a-5e9d-46cb-b97d-f8669d30ab6e","relation":"manager","object":"site:0a5ecb2e-f9b0-463c-a3b1-df0886465bbd"},"contextual_tuples":{"tuple_keys":[]},"authorization_model_id":"01HGSC2RJ3XT4BM1Q27MH50HC8","trace":false,"context":null}, "raw_response": {"allowed":false,"resolution":""}, "peer.address": "127.0.0.1:51082", "store_id": "01H92CEC8HDM58GWGEBRWPQHSS", "authorization_model_id": "01HGSC2RJ3XT4BM1Q27MH50HC8", "grpc_code": 4000, "internal_error": "sql: Scan error on column index 5, name \"condition_name\": converting NULL to string is unsupported"}
```

Example read request:
```
2023-12-05T01:12:16.355Z	ERROR	rpc error: code = Code(4000) desc = Internal Server Error
{"grpc_service": "openfga.v1.OpenFGAService", "grpc_method": "Read", "grpc_type": "unary", "request_id": "12ea7e39-46b7-4480-9b2c-6fde38a61777", "user_agent": "openfga-sdk js/0.2.10", "raw_request": {"store_id":"01H92CEC8HDM58GWGEBRWPQHSS","tuple_key":{"user":"user:8b1ab6bf-bad7-454a-bb4a-c552ff60a6af","relation":"admin","object":"region:US"},"page_size":1,"continuation_token":""}, "raw_response": {"tuples":[],"continuation_token":""}, "peer.address": "127.0.0.1:51082", "store_id": "01H92CEC8HDM58GWGEBRWPQHSS", "grpc_code": 4000, "internal_error": "sql: Scan error on column index 5, name \"condition_name\": converting NULL to string is unsupported"}
```

### PR DESCRIPTION
**Pull request by jpadilla**
## Description

Fixes #1211 

## Review Checklist
- [ ] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [ ] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

File: pkg/storage/mysql/mysql.go [hunk 1]
```diff
@@ -203,10 +206,14 @@ func (m *MySQL) ReadUserTuple(ctx context.Context, store string, tupleKey *openf
 	objectType, objectID := tupleUtils.SplitObject(tupleKey.GetObject())
 	userType := tupleUtils.GetUserTypeFromUser(tupleKey.GetUser())
 
+	var conditionName *string
```
Comment (jon-whit) [inline pkg/storage/mysql/mysql.go:209]:
```suggestion
	var conditionName sql.NullString
```

File: pkg/storage/mysql/mysql_test.go [hunk 2]
```diff
@@ -155,3 +156,27 @@ func TestReadAuthorizationModelUnmarshallError(t *testing.T) {
...
+			condition_name, condition_context, inserted_at
+		) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, NOW());
+	`
+	ulid := ulid.Make().String()
+	_, err = ds.db.ExecContext(ctx, stmt, "store", "folder", "2021-budget", "owner", "user:anne", "user", ulid, nil, nil)
+	require.NoError(t, err)
+
+	tk := tuple.NewTupleKey("folder:2021-budget", "owner", "user:anne")
+	_, err = ds.ReadUserTuple(ctx, "store", tk)
+	require.NoError(t, err)
```
Comment (jon-whit) [inline pkg/storage/mysql/mysql_test.go:181]: Can we also add an assertion just to make sure the tuples condition matches the normalized spec we expect?

File: pkg/storage/postgres/postgres_test.go [hunk 3]
```diff
@@ -154,3 +155,27 @@ func TestReadAuthorizationModelUnmarshallError(t *testing.T) {
...
+			store, object_type, object_id, relation, _user, user_type, ulid,
+			condition_name, condition_context, inserted_at
+		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW());
+	`
+	ulid := ulid.Make().String()
+	_, err = ds.db.ExecContext(ctx, stmt, "store", "folder", "2021-budget", "owner", "user:anne", "user", ulid, nil, nil)
+	require.NoError(t, err)
+
+	tk := tuple.NewTupleKey("folder:2021-budget", "owner", "user:anne")
+	_, err = ds.ReadUserTuple(ctx, "store", tk)
```
Comment (miparnisari) [inline pkg/storage/postgres/postgres_test.go:179]: we also need a test for `ds.ReadChanges` since the new column is also in the `changelog` table

File: pkg/storage/postgres/postgres.go [hunk 4]
```diff
@@ -217,10 +220,14 @@ func (p *Postgres) ReadUserTuple(ctx context.Context, store string, tupleKey *op
 	objectType, objectID := tupleUtils.SplitObject(tupleKey.GetObject())
 	userType := tupleUtils.GetUserTypeFromUser(tupleKey.GetUser())
 
+	var conditionName sql.NullString
```
Comment (miparnisari) [inline pkg/storage/postgres/postgres.go:223]: Why not change the type of `conditionName` inside `TupleRecord`?

**Review by jon-whit — APPROVED** [review]

**Review by miparnisari — APPROVED** [review]
