### PR TITLE
fix: env vars

### LINKED ISSUE #497: OpenFGA v0.3.3: New environment variables are not being respected
**OpenFGA version**: `v0.3.3`
**Reporter**: @xXAvoraXx
**Details**:
The user updated their env variables to our new ones (see [config-schema.json](https://github.com/openfga/openfga/blob/main/.config-schema.json), openfga/openfga#472), e.g.:
- `OPENFGA_RESOLVE_NODE_LIMIT` instead of `OPENFGA_RESOLVENODELIMIT`
- `OPENFGA_LIST_OBJECTS_DEADLINE` instead of `OPENFGA_LISTOBJECTSDEADLINE`

But that caused OpenFGA to ignore those config values and use the default ones instead.

### PR DESCRIPTION
**Pull request by craigpastro**
## Description

Fixes #497.

## Review Checklist
- [ ] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [ ] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

File: cmd/run.go [hunk 1]
```diff
@@ -753,158 +750,158 @@ func RunServer(ctx context.Context, config *Config) error {
 // bindRunFlags binds the cobra cmd flags to the equivalent config value being managed
 // by viper. This bridges the config between cobra flags and viper flags.
 func bindRunFlags(cmd *cobra.Command) {
-
```
Comment (craigpastro) [inline cmd/run.go:756]: What do you think about putting this function into `util.go`? Seems a bit out of place here.

Comment (jon-whit) [reply cmd/run.go:756]: Yeah, that's a good idea. We can colocate it next to the `MustBindPFlag` and `MustBindEnv` command utilities. 👍

**Review by jon-whit — APPROVED** [review]

File: cmd/run.go (hunk 1 above)
Comment (craigpastro) [reply cmd/run.go:756]: Done!

**Review by jon-whit — APPROVED** [review]
